# System stuff
bot = None
db = None
loop = None
cur_presence = None
write_as_token = None
ticking_cooldowns = None
start_dt = None
restart_dt = None

# User configurable vars, Heroku's "Config Vars" are suggested
ADMIN_ID = None
ASSISTANCE_CATEGORY_IDS = None
BLACKLISTED_CHANNELS_IDS = None
BOT_PREFIX = None
CONTRIB_AMOUNT = None
CONTRIB_CHANNELS_IDS = None
CONTRIB_COOLDOWN = None
DAILY_LEVEL_AMOUNT = None
DISCORD_TOKEN = None
HEROKU_TOKEN = None
IMGUR_CLIENT_ID = None
JOIN_LOG_CHANNEL_IDS = None
LEVEL_NOTIF_CHANNEL_IDS = None
MODDER_CATEGORY_IDS = None
MODDER_ROLE_IDS = None
REP_CRED_AMOUNT = None
REQUESTS_CHANNEL_IDS = None
STAFF_ROLE_IDS = None
TROPHY_ROLES = None
WRITE_AS_PASS = None
WRITE_AS_POST_ID = None
WRITE_AS_USER = None
XP_AMOUNT = None
XP_COOLDOWN = None

# Image components
font47 = None
font35 = None
font30 = None
font24 = None
font20 = None
font16 = None
default_avatar = None
overlays_default = None
overlays_staff = None
overlays_admin = None
shards_orange = None
shards_white = None
shards_teal = None
bars = None
levelups = None
