# System stuff
bot = None
config = None
loop = None
cur_presence = None
write_as_token = None
ticking_cooldowns = None

# User configurable vars, Heroku's "Config Vars" are suggested
ADMIN_ID = None
ASSISTANCE_CATEGORY_ID = None
BLACKLISTED_CHANNELS_IDS = None
BOT_PREFIX = None
CONTRIB_AMOUNT = None
CONTRIB_CHANNELS_IDS = None
CONTRIB_COOLDOWN = None
DISCORD_TOKEN = None
JOIN_LOG_CHANNEL_ID = None
MODDER_CATEGORY_IDS = None
MODDER_ROLE_ID = None
ROLE_SELECT_CHANNEL_ID = None
RULES_CHANNEL_ID = None
STAFF_ROLE_ID = None
TROPHY_ROLES = None
WRITE_AS_PASS = None
WRITE_AS_POST_ID = None
WRITE_AS_USER = None
XP_AMOUNT = None
XP_COOLDOWN = None

# Image components
font47 = None
font35 = None
font30 = None
font24 = None
font20 = None
font16 = None
default_avatar = None
overlay = None
staff_overlay = None
shard_orange = None
shard_white = None
bars = None
